//
//  SwiftUIScreenView.swift
//  SwtUIinUIKit
//
//  Created by Mac on 05.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects
//


import SwiftUI

struct SwiftUIScreenView: View {
    
    @Environment(\.colorScheme) var colorScheme
    
    @ObservedObject var intent = SwiftUIScreenIntent()
    
    var body: some View {
        ZStack {
            Text("SwiftUIScreen")
                .foregroundColor(.white)
        }
        .background(Color.red)
    }
    
}

struct SwiftUIScreenView_Previews: PreviewProvider {
    static var previews: some View {
        SwiftUIScreenView()
    }
}
